spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    password: 4021
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:/migration/changelog.xml
